### ISSUE TITLE
There seems to be a problem with the inference process of the MToV model

### ISSUE THREAD

**Issue by 762572251** [KU-CVLAB/MoDiTalker#4]
There are a lot of garbled characters in the code in the MToV folder. When these garbled characters are commented out, new problems will appear. Is there a clearer inference solution?

**Comment by yunyu** [comment]
My attempt at removing the random merge conflicts in the mtov sample.py: https://github.com/yunyu/MoDiTalker/commit/095f734ab4a4e9462d420ae34eab0505f6663eb9
